"""DOC-5: log.md rotation.

Keep the trailing KEEP_DAYS days of entries in `log.md`; move older entries
to `log.archive.YYYY-Q.md` (quarterly buckets). The archive files are
machine-generated and should not be edited manually.

Entry boundary: lines beginning with `## [` (the log.md entry header format).

Scheduled via `wiki rotate-log` (weekly or monthly via cron). Safe to run
multiple times — idempotent: entries already in an archive file are not
re-written.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

from gateway import log, paths
from gateway.core import OperationResult
from gateway.locking import file_lock

KEEP_DAYS: int = 90

_ENTRY_HEADER_RE = re.compile(r"^## \[(\d{4}-\d{2}-\d{2}T[^\]]+)\]")
_ARCHIVE_HEADER = (
    "# Knowledge Log Archive\n\n"
    "Machine-generated archive of `log.md` entries older than {keep_days} days.\n"
    "Do not edit manually. Query via `grep` or `wiki status`.\n"
    "Regenerated by `wiki rotate-log`.\n"
)


def _quarter(dt: datetime) -> str:
    q = (dt.month - 1) // 3 + 1
    return f"{dt.year}-Q{q}"


def _archive_path(quarter: str) -> Path:
    return paths.knowledge_root() / f"log.archive.{quarter}.md"


def _parse_entries(text: str) -> list[tuple[str | None, str]]:
    """Split log text into (iso_timestamp_or_None, entry_text) pairs.

    The first chunk (before any ## header) is the file preamble.
    """
    parts: list[tuple[str | None, str]] = []
    current_lines: list[str] = []
    current_ts: str | None = None

    for line in text.splitlines(keepends=True):
        m = _ENTRY_HEADER_RE.match(line)
        if m:
            if current_lines:
                parts.append((current_ts, "".join(current_lines)))
            current_ts = m.group(1).rstrip("Z").rstrip("+00:00")
            if current_ts.endswith("+00:00"):
                current_ts = current_ts[:-6]
            current_lines = [line]
        else:
            current_lines.append(line)

    if current_lines:
        parts.append((current_ts, "".join(current_lines)))

    return parts


def rotate_log(*, keep_days: int = KEEP_DAYS, dry_run: bool = False) -> OperationResult:
    """Move log entries older than `keep_days` from log.md to quarterly archives."""
    log_path = paths.log_path()
    if not log_path.is_file():
        return OperationResult(success=True, summary="rotate-log: log.md does not exist")

    now = datetime.now(timezone.utc)
    cutoff_ts = now.timestamp() - keep_days * 86400

    with file_lock("log"):
        text = log_path.read_text(encoding="utf-8")

    parts = _parse_entries(text)

    # Separate preamble, recent entries, and old entries
    preamble_lines: list[str] = []
    recent: list[str] = []
    old_by_quarter: dict[str, list[str]] = {}

    for ts, entry in parts:
        if ts is None:
            preamble_lines.append(entry)
            continue
        try:
            # Parse timestamp — support both formats
            clean = ts.replace("Z", "+00:00")
            dt = datetime.fromisoformat(clean)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            entry_ts = dt.timestamp()
        except ValueError:
            recent.append(entry)
            continue

        if entry_ts >= cutoff_ts:
            recent.append(entry)
        else:
            q = _quarter(datetime.fromtimestamp(entry_ts, tz=timezone.utc))
            old_by_quarter.setdefault(q, []).append(entry)

    if not old_by_quarter:
        return OperationResult(
            success=True,
            summary=f"rotate-log: no entries older than {keep_days} days; nothing to rotate",
        )

    archived_count = sum(len(v) for v in old_by_quarter.values())

    if dry_run:
        quarters = sorted(old_by_quarter)
        return OperationResult(
            success=True,
            summary=(
                f"[dry-run] rotate-log: would archive {archived_count} entries "
                f"to {len(quarters)} quarter file(s): {', '.join(quarters)}"
            ),
        )

    # Write archive files
    touched: list[Path] = []
    for quarter, entries in sorted(old_by_quarter.items()):
        archive = _archive_path(quarter)
        header = _ARCHIVE_HEADER.format(keep_days=keep_days)
        if archive.is_file():
            existing = archive.read_text(encoding="utf-8")
            new_text = existing.rstrip() + "\n" + "".join(entries)
        else:
            new_text = header + "".join(entries)
        archive.write_text(new_text, encoding="utf-8")
        touched.append(archive)

    # Rewrite log.md with only recent entries + preamble
    preamble = "".join(preamble_lines)
    if not preamble.strip():
        from gateway.log import _HEADER
        preamble = _HEADER
    new_log = preamble.rstrip() + "\n" + "".join(recent)
    with file_lock("log"):
        log_path.write_text(new_log, encoding="utf-8")
    touched.append(log_path)

    log.append(
        "rotate-log",
        fields={"archived": archived_count, "keep_days": keep_days},
        summary=f"rotated {archived_count} log entries to {len(old_by_quarter)} archive file(s)",
    )

    return OperationResult(
        success=True,
        paths_touched=touched,
        summary=(
            f"rotate-log: archived {archived_count} entries; "
            f"log.md retains {len(recent)} recent entries; "
            f"archive files: {', '.join(sorted(old_by_quarter))}"
        ),
    )
